
package util.webservices.fechamentos;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "rubi_Synccom.senior.g5.rh.fp.doug.fechamentos", targetNamespace = "http://services.senior.com.br")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RubiSynccomSeniorG5RhFpDougFechamentos {


    /**
     * 
     * @param encryption
     * @param parameters
     * @param password
     * @param user
     * @return
     *     returns util.webservices.fechamentos.SynccomSeniorG5RhFpDougFechamentosAfastamentosOut
     */
    @WebMethod(operationName = "Afastamentos")
    @WebResult(name = "result", partName = "result")
    @Action(input = "http://services.senior.com.br/rubi_Synccom.senior.g5.rh.fp.doug.fechamentos/AfastamentosRequest", output = "http://services.senior.com.br/rubi_Synccom.senior.g5.rh.fp.doug.fechamentos/AfastamentosResponse")
    public SynccomSeniorG5RhFpDougFechamentosAfastamentosOut afastamentos(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "encryption", partName = "encryption")
        int encryption,
        @WebParam(name = "parameters", partName = "parameters")
        SynccomSeniorG5RhFpDougFechamentosAfastamentosIn parameters);

    /**
     * 
     * @param encryption
     * @param parameters
     * @param password
     * @param user
     * @return
     *     returns util.webservices.fechamentos.SynccomSeniorG5RhFpDougFechamentosColaboradoresVinculadosOut
     */
    @WebMethod(operationName = "ColaboradoresVinculados")
    @WebResult(name = "result", partName = "result")
    @Action(input = "http://services.senior.com.br/rubi_Synccom.senior.g5.rh.fp.doug.fechamentos/ColaboradoresVinculadosRequest", output = "http://services.senior.com.br/rubi_Synccom.senior.g5.rh.fp.doug.fechamentos/ColaboradoresVinculadosResponse")
    public SynccomSeniorG5RhFpDougFechamentosColaboradoresVinculadosOut colaboradoresVinculados(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "encryption", partName = "encryption")
        int encryption,
        @WebParam(name = "parameters", partName = "parameters")
        SynccomSeniorG5RhFpDougFechamentosColaboradoresVinculadosIn parameters);

    /**
     * 
     * @param encryption
     * @param parameters
     * @param password
     * @param user
     * @return
     *     returns util.webservices.fechamentos.SynccomSeniorG5RhFpDougFechamentosVagasAutorizadasOut
     */
    @WebMethod(operationName = "VagasAutorizadas")
    @WebResult(name = "result", partName = "result")
    @Action(input = "http://services.senior.com.br/rubi_Synccom.senior.g5.rh.fp.doug.fechamentos/VagasAutorizadasRequest", output = "http://services.senior.com.br/rubi_Synccom.senior.g5.rh.fp.doug.fechamentos/VagasAutorizadasResponse")
    public SynccomSeniorG5RhFpDougFechamentosVagasAutorizadasOut vagasAutorizadas(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "encryption", partName = "encryption")
        int encryption,
        @WebParam(name = "parameters", partName = "parameters")
        SynccomSeniorG5RhFpDougFechamentosVagasAutorizadasIn parameters);

}
